#!/bin/bash

# One of the following: xrandr, light, kernel
METHOD="light"

curBrightness=$(light)
percent=$(echo "scale=0;${curBrightness}" | bc -l)
#percent=${percent%.*}
percent=$(light | cut -d . -f 1)

# Left click
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  light -A 1
# Right click
elif [ "${BLOCK_BUTTON}" -eq 5 ] && [ ${percent} -gt 1 ]; then
  light -U 1
elif [ "${BLOCK_BUTTON}" -eq 3 ]; then
  light -U 0.1
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  light -A 0.1
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  light -S 100
fi

URGENT_VALUE=10

if [[ "${METHOD}" = "xrandr" ]]; then
  device="${BLOCK_INSTANCE:-primary}"
  xrandrOutput=$(xrandr --verbose)

  if [[ "${device}" = "primary" ]]; then
    device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
  fi

  curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
  device="${BLOCK_INSTANCE:-intel_backlight}"
  maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
  curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "light" ]]; then
  curBrightness=$(light)
fi

#if [[ "${curBrightness}" -le 0 ]]; then
#  exit
#fi

if [[ "${METHOD}" = "xrandr" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100 / ${maxBrightness}" | bc -l)
elif [[ "${METHOD}" = "light" ]]; then
  percent=$(echo "scale=0;${curBrightness}" | bc -l)
fi

#percent=${percent%.*}
percent=$(light)

#if [[ "${percent}" -le 0 ]]; then
#  exit
#fi

#echo "${percent}%"
#echo "${percent}%"
#echo ""

#if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
#  exit 33
#fi

LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}
echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">BL ${percent}%</span>"

