#!/bin/bash

if [[ $(ps aux | grep trackact | grep -v vim  | grep -v grep | wc -l) -gt 3 ]]; then
	TRACKING_STATE="TRACKING"
else
	TRACKING_STATE="NOT tracking"
fi

LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}
echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$TRACKING_STATE </span>"

